apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-app
  namespace: exam-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-app
  template:
    metadata:
      labels:
        app: exam-app
    spec:
      containers:
        - name: lighttpd-container
          image: lighttpd:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "4"
              memory: "1Gi"
          volumeMounts:
            - name: shared-storage
              mountPath: /var/www/localhost/htdocs

        - name: logger-container
          image: busybox
          command: ["sh", "-c", "while true; do date >> /logs/log.txt; sleep 10; done"]
          volumeMounts:
            - name: shared-storage
              mountPath: /logs

      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: exam-shared-pvc